version: '3.7'

services:
  frontend:
    container_name: frontend
    image: node:12-alpine
    command: yarn run dev
    volumes:
      - ./frontend:/frontend
    working_dir: /frontend
    ports:
      - "3000:3000"
    environment:
      API_URL: http://backend:1337
      HOST: 0.0.0.0
    depends_on:
      - backend

  backend:
    container_name: backend
    image: strapi/strapi
    volumes:
      - ./backend/:/srv/app
      - backend_node_modules/:/srv/app/node_modules
    ports:
      - '1337:1337'
    environment:
      NODE_ENV: production
      DATABASE_CLIENT: postgres
      CLOUDINARY_NAME: "${CLOUDINARY_NAME}"
      CLOUDINARY_KEY: "${CLOUDINARY_KEY}"
      CLOUDINARY_SECRET: "${CLOUDINARY_SECRET}"
      SMTP_HOST: "${SMTP_HOST}"
      SMTP_PORT: "${SMTP_PORT}"
      SMTP_USERNAME: "${SMTP_USERNAME}"
      SMTP_PASSWORD: "${SMTP_PASSWORD}"
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: postgres
      DATABASE_USERNAME: "${POSTGRES_USER}"
    depends_on:
      - db

  db:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: "${POSTGRES_USER}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports: [ '5432:5432' ]

volumes:
  postgres_data:
  backend_node_modules:
