name: Continuous deployment

on:
  push:
    branches:
      - deployment

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.4.6 # This is the action
        with:
          heroku_app_name: "werkhof-ichen-backend" #Must be unique in Heroku
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          appdir: backend
      - shell: bash
        env:
          NETLIFY_WEBHOOK: ${{ secrets.NETLIFY_WEBHOOK }}
        run: |
          curl -X POST -d {} "$NETLIFY_WEBHOOK"
